version: '3'
services:
  ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - api
  api:
    image: my-api
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: my-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r


# connect (api, db, ui)
# docker-compose up -d